version: '3.8'

services:
  soplang:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/app
    command: bash 